### ISSUE TITLE
该组件库支持哪些小程序

### ISSUE THREAD

**Issue by xuanxuan321** [mxdi9i7/vant-react#111]
这个库支持哪些小程序，是只支持微信小程序吗

**Comment by IlhamTahir** [comment]
> 这个库支持哪些小程序，是只支持微信小程序吗



@xuanxuan321 
你好，这是Vant的React版本，不支持小程序。Vant微信小程序版本：https://github.com/youzan/vant
另外我看还有几个Taro版本的Vant也可以咨询一下是否满足你的需求。 https://github.com/Reamd7/taro-vant
