### ISSUE TITLE
没轮播组件 swiper吗？

### ISSUE THREAD

**Issue by marlti7** [mxdi9i7/vant-react#114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 3lang3** [comment]
@marlti7 https://github.com/3lang3/react-vant 试试这个

**Comment by mxdi9i7** [comment]
@marlti7 暂时没有，之前有一个pr有提swiper，但是bug太多关掉了，你可以自己提一个PR
