### ISSUE TITLE
文档中Field组件onChange事件未更新，目前是旧的input事件

### ISSUE THREAD

**Issue by ezzhu** [mxdi9i7/vant-react#115]
version 0.3.1

**Comment by mxdi9i7** [comment]
旧的input事件是啥意思，可以给个例子嘛？

**Comment by ezzhu** [comment]
> �旧的input事件是啥意思，可以给个例子嘛？

没看错的话，该文档中的https://bctc.gitbook.io/vant-react-official-docs/field#api Event input 应该是更名为onChange了，文档可能没有更新过来。
![image](https://user-images.githubusercontent.com/31620716/134441452-a1fa8ce7-0eae-4a33-b2db-1a7b2ef4708b.png)
