### ISSUE TITLE
一些个人建议

### ISSUE THREAD

**Issue by Qinmei** [mxdi9i7/vant-react#46]
无意中看到这个项目，react在移动端确实很薄弱， 能有这个项目确实很不错， 以下是一些个人建议：

文档：目前demo跟文档完全是脱离的，建议直接使用dumi之类的来构建文档， 同时可以直接展示demo。

按需引入：不需要再引入一个index.css;

组件基础：antd的底层是[react-component](http://react-component.github.io/badgeboard/), 移动端应该是可以直接使用一部分的；

最后， 感谢大家的开发

**Comment by ssysm** [comment]
感谢对Vant React的支持！
在文档这方面，我们已经有计划合并Gitbook和Storyboard，但是这需要一段时间合并

index.css引入问题可以等@mxdi9i7 来解答一下

**Comment by mxdi9i7** [comment]
@Qinmei 
按需引入：有计划做code splitting(按需引入)，但需要在basic components都做完之后处理了。
文档：文档方面的话我们本来也想一步到位直接结合storybook的demo和docs的文档。但是在了解过一些工具后发现工作量有点大，打算等项目进展到接近1.0正式发布的时候再着手去做一个好用的文档系统。现在的文档基本都是面向开发人员写的。

总结一下：就是非常缺人手，很多想做的事情只能先backlog一下，等核心组件做完了再去做那些backlog

**Comment by atom-shanghai** [comment]
非常支持，不知道官方计划什么时候发版

**Comment by GenesisLQ** [comment]
目前是 React 技术栈，有意加入团队一起完善 vant-react 版本
