### ISSUE TITLE
文档中关于popup的size属性错了，最新代码是传入的{width: xx, height: xx}对象

### ISSUE THREAD

**Issue by yuhang1995** [mxdi9i7/vant-react#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mxdi9i7** [comment]
@WillHHH  Please take a look into this issue and work with @trista8130 to update docs if needed

**Comment by WillHHH** [comment]
> @WillHHH Please take a look into this issue and work with @trista8130 to update docs if needed

Fixed on git book.
