### ISSUE TITLE
1.2.1版本中上传图片使用的参数是file.path，升级到1.6.2参数变成了file.url导致所有上传图片异常

### ISSUE THREAD

**Issue by zzhn6** [mxdi9i7/vant-react#96]
![1](https://user-images.githubusercontent.com/29200763/103201210-53e67b80-492a-11eb-9a97-2ab42ede3af1.png)
![2](https://user-images.githubusercontent.com/29200763/103201285-81332980-492a-11eb-8230-86493400615b.png)

**Comment by mxdi9i7** [comment]
这里是vant-react项目，你应该走错了
